# --- Potential specific parameters ---
mac: "global_mac" # Basic controller
agent: "global"

action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 500000
mask_before_softmax: False

runner: "parallel"
batch_size_run: 4

buffer_size: 5000

env_args:
  state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval: 200

lr: 0.0005
global_lr: 0.0005
#td_lambda: 0.8

# use COMA
agent_output_type: "q"
learner: "potential_q_learner"
double_q: True

name: "potential_only_global_smac"
